user                    nginx;
worker_processes        auto;
worker_rlimit_nofile    65535;

#notice
error_log               /var/log/nginx/error.log notice;
pid                     /var/run/nginx.pid;

#load_module             /etc/nginx/modules/ngx_http_js_module.so;

events {
    use                 epoll;
    worker_connections  10240;
}

http {
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    #include             /etc/nginx/conf.d/conf_js;
    include             /etc/nginx/conf.d/conf_map;

    log_format          main  '[$time_local] $status "$request" $request_time - $request_length,$body_bytes_sent - $remote_addr';
    access_log          /var/log/nginx/access.log  main if=$loggable_status;

    sendfile            on;
    #tcp_nopush         on;

    keepalive_timeout   65;

    #gzip               on;
    server_tokens       off;
    dav_methods         off;

    include             /etc/nginx/conf.d/conf_header;
    include             /etc/nginx/conf.d/conf_proxy_header;
    include             /etc/nginx/conf.d/conf_hide_header;

    include /etc/nginx/conf.d/*.conf;
}